name: GitHub Action
on:
  push:
    branches:
      - main
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3,
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          node-version: "14.15.0"
      - run: npm install
      - run: npm run build
      - run: npm upgrade -g heroku
      - uses: akhileshns/heroku-deploy@v3.12.12
      with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "JESSICA MELISE FEITOSA"
          heroku_email: "felipe@stabel.com.br"